name: Application

on:
  push:
    branches: [ "master", "stage" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Raise containers
      run: docker compose up -d --build

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --ignore-platform-reqs

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run PHPStan
      run: docker exec app_web php vendor/bin/phpstan analyse --level 9 src/

    - name: Run Psalm
      run: docker exec app_web php vendor/bin/psalm

    - name: Run PHPUnit
      run: docker exec app_web php vendor/bin/phpunit
